---

- name: install deps
  yum: name={{ item }} state=latest
  with_items: grpr_yum_deps

- name: create dir
  file: path=/srv/grouper state=directory mode=0755 owner=vagrant group=vagrant

- name: download components
  get_url: url="http://software.internet2.edu/grouper/release/{{grpr_ver}}/grouper.{{item}}-{{grpr_ver}}.tar.gz" dest=/tmp
  with_items: grpr_components

- name: unarchive components
  unarchive: src=/tmp/grouper.{{item}}-{{grpr_ver}}.tar.gz dest=/srv/grouper owner=vagrant group=vagrant
  with_items: grpr_components
